### ISSUE TITLE
Fix Difficulty Unit Test

### ISSUE THREAD

**Issue by Seraphyno** [Seraphyno/Climber#4]
Fix Difficulty Unit Test.

Initial error: 

`Class not found: "enums.DifficultyTest"Empty test suite.`

Error after changing classpath:

```
!!! JUnit version 3.8 or later expected:

java.lang.ClassNotFoundException: junit.framework.ComparisonFailure
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.junit.JUnitStarter.junitVersionChecks(JUnitStarter.java:221)
	at com.intellij.rt.execution.junit.JUnitStarter.canWorkWithJUnitVersion(JUnitStarter.java:207)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
```

**Comment by Seraphyno** [comment]
- [ ] Check the name of the package
- [ ] Check that `@Test`, `@Before` come from the right `junit` dependency

**Comment by Seraphyno** [comment]
Issue cause was:
- [ ] Missing configuration for maven-surefire
- [ ] Incorrect folder structure in `src/test/java`
